package server

import "github.com/gin-gonic/gin"

func registerRoutes(r *gin.Engine, ds *DashboardServer) {
	api := r.Group("/api")
	{
		api.GET("/health", ds.apiHealth)
		api.GET("/status", ds.apiStatus)
		api.GET("/metrics", ds.apiMetrics)
		api.GET("/events", ds.apiSSE)
		api.POST("/headroom/start", ds.apiHeadroomStartPM)
		api.POST("/headroom/stop", ds.apiHeadroomStopPM)
		api.GET("/rtk/gain", ds.apiRTKGain)
		api.POST("/codebase/index", ds.apiCodebaseIndex)
		api.GET("/codebase/index/status", ds.apiCodebaseIndexStatus)
		api.POST("/setup/save", ds.apiSetupSave)
		api.GET("/setup/load", ds.apiSetupLoad)
		api.GET("/setup/status", ds.apiSetupStatus)
		api.GET("/fs/browse", ds.apiFsBrowse)
		api.POST("/services/start-all", ds.apiServicesStartAll)
		api.POST("/services/stop-all", ds.apiServicesStopAll)
		api.GET("/services/status", ds.apiServicesStatus)
		api.GET("/logs", ds.apiLogs)
		api.POST("/setup/install", ds.apiSetupInstall)
		api.GET("/install/status", ds.apiInstallStatus)
		api.GET("/cwd", ds.apiCwd)
		api.GET("/tool-details", ds.apiToolDetails)
		api.GET("/context", ds.apiContext)
		api.POST("/codebase/open-ui", ds.apiCodebaseOpenUI)
		api.GET("/headroom/stats-url", ds.apiHeadroomStatsURL)
		api.POST("/project/switch", ds.apiProjectSwitch)
		api.GET("/projects", ds.apiProjectsList)
		api.GET("/projects/current", ds.apiProjectsCurrent)
		api.GET("/obsidian/status", ds.apiObsidianStatus)
		api.GET("/obsidian/search", ds.apiObsidianSearch)
		api.POST("/obsidian/save", ds.apiObsidianSave)
		api.POST("/obsidian/context", ds.apiObsidianSaveContext)
		api.POST("/obsidian/summarize", ds.apiObsidianSummarize)
		api.POST("/obsidian/open", ds.apiObsidianOpen)
		api.POST("/obsidian/open-dir", ds.apiObsidianOpenDir)
		api.POST("/obsidian/install", ds.apiObsidianInstall)
		api.GET("/obsidian/install-status", ds.apiObsidianInstallStatus)
		api.POST("/services/codebase/start", ds.apiCodebaseStart)
		api.POST("/services/codebase/stop", ds.apiCodebaseStop)
		api.GET("/services/codebase/status", ds.apiCodebaseStatus)
		api.GET("/services/codebase/logs", ds.apiCodebaseLogs)
		api.POST("/services/headroom/start", ds.apiHeadroomStartPM)
		api.POST("/services/headroom/stop", ds.apiHeadroomStopPM)
		api.GET("/services/headroom/status", ds.apiHeadroomStatusPM)
		api.GET("/services/headroom/logs", ds.apiHeadroomLogsPM)
		api.GET("/state", ds.apiState)
		api.GET("/mcp/registry", ds.apiMCPRegistry)
		api.POST("/mcp/configure", ds.apiMCPConfigure)
		api.POST("/mcp/services/start", ds.apiMCPStart)
		api.POST("/mcp/services/stop", ds.apiMCPStop)
		api.POST("/mcp/services/restart", ds.apiMCPRestart)
		api.GET("/mcp/services/status", ds.apiMCPStatus)
		api.GET("/mcp/services/logs", ds.apiMCPLogs)
		api.GET("/kiro/power/status", ds.apiKiroPowerStatus)
		api.POST("/kiro/power/refresh", ds.apiKiroPowerRefresh)
	}
}
